### ISSUE TITLE
Issues that it counts wrong

### ISSUE THREAD

**Issue by dimkauzh** [aschey/vercel-tokei#59]
Hi, so I have had issues with original tokei.rs, so i found this. It looked very promising, but i found a issue from the start: It doesn't count all lines. I have [my repo](https://github.com/dimkauzh/fusion-engine), and as you see in this screenshot
<img width="720" alt="Screenshot 2023-12-31 at 15 37 48" src="https://github.com/aschey/vercel-tokei/assets/106883655/fed9928b-aa5c-4b98-bc54-6064dbde4695">
It's 4003 lines. But [my badge](https://www.aschey.tech/tokei/github/dimkauzh/fusion-engine) shows only 1.4k lines.
<img width="119" alt="Screenshot 2023-12-31 at 15 38 48" src="https://github.com/aschey/vercel-tokei/assets/106883655/fb547dfc-ef88-4f69-b6e2-f5b39d805e49">

**Comment by aschey** [comment]
Hi @dimkauzh, thanks for the issue report! It seems that tokei.rs uses total lines by default whereas I configured this to use lines of code. Not sure if this was a miss on my part or if something changed in tokei since I created this. I changed this to also use total lines by default now so this should be resolved.

**Comment by dimkauzh** [comment]
> Hi @dimkauzh, thanks for the issue report! It seems that tokei.rs uses total lines by default whereas I configured this to use lines of code. Not sure if this was a miss on my part or if something changed in tokei since I created this. I changed this to also use total lines by default now so this should be resolved.

Oh okay thank you! Have a nice day! Good luck with developing this further!
